APP_PLATFORM=android-23
APP_ABI = arm64-v8a
APP_STL=c++_static
NDK_TOOLCHAIN_VERSION = clang
APP_STRIP_MODE = --strip-unneeded
APP_OPTIM = release
APP_THIN_ARCHIVE = true
APP_PIE 		= true
APP_HOST_OS = linux